package com.nnpg.glazed.utils;

import com.nnpg.glazed.mixins.CountPlacementAccessor;
import com.nnpg.glazed.mixins.HeightRangePlacementAccessor;
import com.nnpg.glazed.mixins.RarityFilterAccessor;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.HolderSet;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.registries.VanillaRegistries;
import net.minecraft.data.worldgen.placement.OrePlacements;
import net.minecraft.resources.ResourceKey;
import net.minecraft.util.valueproviders.ConstantInt;
import net.minecraft.util.valueproviders.IntProvider;
import net.minecraft.world.level.LevelHeightAccessor;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.biome.FeatureSorter;
import net.minecraft.world.level.chunk.ChunkGenerator;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.dimension.LevelStem;
import net.minecraft.world.level.levelgen.GenerationStep;
import net.minecraft.world.level.levelgen.WorldGenerationContext;
import net.minecraft.world.level.levelgen.feature.ScatteredOreFeature;
import net.minecraft.world.level.levelgen.feature.configurations.FeatureConfiguration;
import net.minecraft.world.level.levelgen.feature.configurations.OreConfiguration;
import net.minecraft.world.level.levelgen.heightproviders.HeightProvider;
import net.minecraft.world.level.levelgen.placement.CountPlacement;
import net.minecraft.world.level.levelgen.placement.HeightRangePlacement;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;
import net.minecraft.world.level.levelgen.placement.PlacementModifier;
import net.minecraft.world.level.levelgen.placement.RarityFilter;
import net.minecraft.world.level.levelgen.presets.WorldPresets;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The vanilla ore placements that run in the overworld, with the numbers that decide where each
 * vein lands. Same idea as {@link NetherOre}, two things differ:
 *
 *   - the generation step is UNDERGROUND_ORES (ordinal 6, 34 features) rather than
 *     UNDERGROUND_DECORATION
 *   - every one of these features is a plain OreFeature, so nothing here takes the scattered path
 *
 * {@link #index} is the feature's position in the flattened list of every feature that runs at
 * that step across every overworld biome, and setFeatureSeed(populationSeed, index, step) is what
 * turns the world seed into vein positions. The ordering comes out of FeatureSorter on the real
 * vanilla data, so it is exact rather than guessed.
 */
public class OverworldOre {

    public enum Type {
        // real ores. Anti-xray hides these when they are buried, so a prediction can only be
        // checked against ones that are already exposed.
        EMERALD(true, false),
        DIAMOND(true, false),
        GOLD(true, false),
        IRON(true, false),
        COAL(true, false),
        REDSTONE(true, false),
        LAPIS(true, false),
        COPPER(true, false),

        // generated by the same UNDERGROUND_ORES pipeline but not ores as far as anti-xray is
        // concerned, so the server sends them truthfully even when buried. That makes them the
        // only way to check the seed and the feature ordering without mining anything.
        // dirt, gravel and clay also come from surface generation that has nothing to do with
        // these features, so most of the blocks you find are not ones we predict and their
        // numbers mean nothing. Only the four stone variants are clean references.
        DIRT(false, false),
        GRAVEL(false, false),
        CLAY(false, false),
        GRANITE(false, true),
        DIORITE(false, true),
        ANDESITE(false, true),
        TUFF(false, true);

        /** True when anti-xray hides buried blocks of this type. */
        public final boolean hidden;
        /** True when every block of this type in the world came from these ore features. */
        public final boolean reference;

        Type(boolean hidden, boolean reference) {
            this.hidden = hidden;
            this.reference = reference;
        }
    }

    private static volatile Map<ResourceKey<Biome>, List<OverworldOre>> cache;
    private static volatile List<OverworldOre> allCache;

    public final Type type;
    /** Feature name, e.g. ore_granite_upper. Two variants of one ore share a Type but not this. */
    public final String name;
    public final int step;
    public final int index;
    public final int size;
    public final float discardOnAirChance;
    public final boolean scattered;
    /** What vanilla is allowed to replace: the stone and deepslate replaceable tags. */
    public final List<OreConfiguration.TargetBlockState> targetStates;
    public final BlockState oreState;
    /** Every block this feature can leave behind, e.g. emerald_ore and deepslate_emerald_ore. */
    public final List<Block> resultBlocks;
    public final IntProvider count;
    public final HeightProvider heightProvider;
    public final WorldGenerationContext heightContext;
    public final int rarity;

    private OverworldOre(PlacedFeature feature, Type type, String name, int step, int index, WorldGenerationContext heightContext) {
        this.type = type;
        this.name = name;
        this.step = step;
        this.index = index;
        this.heightContext = heightContext;

        IntProvider count = ConstantInt.of(1);
        HeightProvider height = null;
        int rarity = 1;

        for (PlacementModifier modifier : feature.placement()) {
            if (modifier instanceof CountPlacement) count = ((CountPlacementAccessor) modifier).getCount();
            else if (modifier instanceof HeightRangePlacement) height = ((HeightRangePlacementAccessor) modifier).getHeight();
            else if (modifier instanceof RarityFilter) rarity = ((RarityFilterAccessor) modifier).getChance();
        }

        this.count = count;
        this.heightProvider = height;
        this.rarity = rarity;

        FeatureConfiguration config = feature.feature().value().config();
        if (!(config instanceof OreConfiguration ore)) {
            throw new IllegalStateException("placed feature is not an ore: " + name);
        }

        this.targetStates = ore.targetStates;
        this.oreState = ore.targetStates.isEmpty() ? null : ore.targetStates.get(0).state;
        this.size = ore.size;
        this.discardOnAirChance = ore.discardChanceOnAirExposure;
        this.scattered = feature.feature().value().feature() instanceof ScatteredOreFeature;

        List<Block> results = new ArrayList<>();
        for (OreConfiguration.TargetBlockState target : ore.targetStates) {
            Block block = target.state.getBlock();
            if (!results.contains(block)) results.add(block);
        }
        this.resultBlocks = List.copyOf(results);
    }

    // kept from the first build so SeedWorld can run vanilla biome and terrain lookups off the
    // same registry instead of paying for a second createLookup()
    private static volatile HolderLookup.Provider registryCache;
    private static volatile ChunkGenerator generatorCache;
    private static volatile LevelHeightAccessor heightsCache;

    /** Null until {@link #get} has run once. */
    public static HolderLookup.Provider registry() {
        return registryCache;
    }

    /** The vanilla overworld generator, for biome and terrain height straight from the seed. */
    public static ChunkGenerator generator() {
        return generatorCache;
    }

    public static LevelHeightAccessor heights() {
        return heightsCache;
    }

    /**
     * Builds the biome to ore map from the vanilla worldgen data shipped inside the client jar.
     * Costs a second or so the first time, so the result is cached. Height values are passed in
     * rather than read off the level, so this is safe to run off the main thread.
     */
    public static synchronized Map<ResourceKey<Biome>, List<OverworldOre>> get(int minY, int height) {
        if (cache != null) return cache;

        HolderLookup.Provider registry = VanillaRegistries.createLookup();
        registryCache = registry;
        HolderLookup.RegistryLookup<PlacedFeature> placed = registry.lookupOrThrow(Registries.PLACED_FEATURE);

        LevelStem overworld = WorldPresets.createNormalWorldDimensions(registry).dimensions().get(LevelStem.OVERWORLD);
        List<Holder<Biome>> biomes = overworld.generator().getBiomeSource().possibleBiomes().stream().toList();

        List<FeatureSorter.StepFeatureData> indexer = FeatureSorter.buildFeaturesPerStep(
            biomes, biome -> biome.value().getGenerationSettings().features(), true);

        int step = GenerationStep.Decoration.UNDERGROUND_ORES.ordinal();

        generatorCache = overworld.generator();

        LevelHeightAccessor heights = LevelHeightAccessor.create(minY, height);
        heightsCache = heights;
        // 26.1.2 dereferences the generator in this constructor, so a null one crashes here
        WorldGenerationContext heightContext = new WorldGenerationContext(overworld.generator(), heights);

        // insertion ordered so the diagnostics print in a stable, readable order
        Map<PlacedFeature, OverworldOre> byFeature = new LinkedHashMap<>();

        register(byFeature, indexer, placed, OrePlacements.ORE_EMERALD, Type.EMERALD, "ore_emerald", step, heightContext);

        register(byFeature, indexer, placed, OrePlacements.ORE_DIAMOND, Type.DIAMOND, "ore_diamond", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_DIAMOND_MEDIUM, Type.DIAMOND, "ore_diamond_medium", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_DIAMOND_LARGE, Type.DIAMOND, "ore_diamond_large", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_DIAMOND_BURIED, Type.DIAMOND, "ore_diamond_buried", step, heightContext);

        register(byFeature, indexer, placed, OrePlacements.ORE_GOLD, Type.GOLD, "ore_gold", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_GOLD_LOWER, Type.GOLD, "ore_gold_lower", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_GOLD_EXTRA, Type.GOLD, "ore_gold_extra", step, heightContext);

        register(byFeature, indexer, placed, OrePlacements.ORE_IRON_UPPER, Type.IRON, "ore_iron_upper", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_IRON_MIDDLE, Type.IRON, "ore_iron_middle", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_IRON_SMALL, Type.IRON, "ore_iron_small", step, heightContext);

        register(byFeature, indexer, placed, OrePlacements.ORE_COAL_UPPER, Type.COAL, "ore_coal_upper", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_COAL_LOWER, Type.COAL, "ore_coal_lower", step, heightContext);

        register(byFeature, indexer, placed, OrePlacements.ORE_REDSTONE, Type.REDSTONE, "ore_redstone", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_REDSTONE_LOWER, Type.REDSTONE, "ore_redstone_lower", step, heightContext);

        register(byFeature, indexer, placed, OrePlacements.ORE_LAPIS, Type.LAPIS, "ore_lapis", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_LAPIS_BURIED, Type.LAPIS, "ore_lapis_buried", step, heightContext);

        register(byFeature, indexer, placed, OrePlacements.ORE_COPPER, Type.COPPER, "ore_copper", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_COPPER_LARGE, Type.COPPER, "ore_copper_large", step, heightContext);

        register(byFeature, indexer, placed, OrePlacements.ORE_DIRT, Type.DIRT, "ore_dirt", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_GRAVEL, Type.GRAVEL, "ore_gravel", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_GRANITE_UPPER, Type.GRANITE, "ore_granite_upper", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_GRANITE_LOWER, Type.GRANITE, "ore_granite_lower", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_DIORITE_UPPER, Type.DIORITE, "ore_diorite_upper", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_DIORITE_LOWER, Type.DIORITE, "ore_diorite_lower", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_ANDESITE_UPPER, Type.ANDESITE, "ore_andesite_upper", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_ANDESITE_LOWER, Type.ANDESITE, "ore_andesite_lower", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_TUFF, Type.TUFF, "ore_tuff", step, heightContext);
        register(byFeature, indexer, placed, OrePlacements.ORE_CLAY, Type.CLAY, "ore_clay", step, heightContext);

        Map<ResourceKey<Biome>, List<OverworldOre>> byBiome = new HashMap<>();

        for (Holder<Biome> biome : biomes) {
            ResourceKey<Biome> key = biome.unwrapKey().orElse(null);
            if (key == null) continue;

            List<OverworldOre> ores = new ArrayList<>();
            biome.value().getGenerationSettings().features().stream()
                .flatMap(HolderSet::stream)
                .map(Holder::value)
                .filter(byFeature::containsKey)
                .forEach(feature -> ores.add(byFeature.get(feature)));

            byBiome.put(key, List.copyOf(ores));
        }

        allCache = List.copyOf(byFeature.values());
        cache = Map.copyOf(byBiome);
        return cache;
    }

    /** Every registered placement, in the order above, whether or not a biome uses it. */
    public static List<OverworldOre> all() {
        return allCache;
    }

    /** Dropped when you leave the world, since the height context is tied to the dimension. */
    public static synchronized void invalidate() {
        cache = null;
        allCache = null;
        registryCache = null;
        generatorCache = null;
        heightsCache = null;
    }

    private static void register(
        Map<PlacedFeature, OverworldOre> map,
        List<FeatureSorter.StepFeatureData> indexer,
        HolderLookup.RegistryLookup<PlacedFeature> placed,
        ResourceKey<PlacedFeature> key,
        Type type,
        String name,
        int step,
        WorldGenerationContext heightContext
    ) {
        PlacedFeature feature = placed.getOrThrow(key).value();
        int index = indexer.get(step).indexMapping().applyAsInt(feature);
        if (index < 0) {
            throw new IllegalStateException(key.identifier() + " is not registered in decoration step " + step);
        }
        map.put(feature, new OverworldOre(feature, type, name, step, index, heightContext));
    }
}
